config/routes.rb
PanTcga::Application.routes.draw do
  
  root  'welcome#index', via: [:get, :post]
  
  match 'about', to: 'static_pages#about', via: 'get'
  match 'faq', to: 'static_pages#faq', via: 'get'
  match 'project_overview', to: 'static_pages#project_overview', via: 'get'
  match 'analysis_pipeline', to: 'static_pages#analysis_pipeline', via: 'get'
  match 'target_selection', to: 'static_pages#target_selection', via: 'get'
  match 'data_information', to: 'static_pages#data_information', via: 'get'
  match 'data_download', to: 'static_pages#data_download', via: 'get'
  match 'show_target_selection_file' => 'static_pages#show_target_selection_file', via: 'get'
  match 'target_selection_send_data' => 'static_pages#target_selection_send_data', via: 'get'
  match 'tutorial' => 'static_pages#tutorial_overview', via: 'get'
  match 'ppt_sendfile' => 'static_pages#ppt_sendfile', via: 'get'
  match 'send_zip_file' => 'static_pages#send_zip_file', via: [:get, :post]
  
  match '/get_cancer_type', to: 'cancer_types#get_cancer_type', via: 'post'

  match 'high_level_summary', to: 'high_level_summaries#index', via: [:get, :post]
  match 'show_high_level_summary_panels', to: 'high_level_summaries#show_high_level_summary_panels', via: [:get, :post]
  match 'high_level_summary_table', to: 'high_level_summaries#show_table', via: 'post'
  match 'high_level_data_analysis', to: 'high_level_summaries#high_level_data_analysis', via: [:get, :post]
  match 'query_clin_param_vals', to: 'high_level_summaries#query_clin_param_vals', via: [:get, :post]

  match 'outcome_summary', to: 'outcome_summaries#index', via: [:get, :post]
  match 'search_outcome_tables', to: 'outcome_summaries#search_outcome_tables', via: [:get, :post]
  match 'send_file' => 'outcome_summaries#send_file', via: [:get, :post]

  match 'matrix_query', to: 'matrix#index', via: [:get, :post]
  match 'target_genomic_query', to: 'matrix#target_genomic_by_target_genomic', via: [:get, :post] 
  match 'get_matrix_data', to: 'matrix#get_matrix_data', via: [:get, :post] 

  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def faq
  end
  
  def about
    @versions = Version::ALLVERSIONS
  end
  
  def contact
  end
  
  def project_overview
  end
  
  def analysis_pipeline
  end
  
  def target_selection
    if Version::CURRENT_VERSION.version_number == '1.0'
      render 'target_selection_v1'
    else
      render 'target_selection'
    end
  end

  def tutorial_overview
    
  end

  def data_information
    # UNCOMMENT THESE FOR INITIAL LOAD OF DATA TABLE WITH 'data_information_query_table' partial
    # AFTERWARDS, COMMENT THEM BACK OUT. TOTAL QUERY TIME IS TOO SLOW
    #@cancer_types = CancerType.where.not(abbreviation: ['COAD', 'READ']).order(:abbreviation)
    #@samples = Sample.select(:id, :cancer_type_id)
    #@gene_values = TargetGeneValue.select(:sample_id, :cancer_type_id).group(:sample_id)
    #@protein_values = TargetProteinValue.select(:sample_id, :cancer_type_id).group(:sample_id)
    #@mir_values = TargetMirValue.select(:sample_id, :cancer_type_id).group(:sample_id)
    @cancer_types = CancerType.order(:abbreviation)
    @cancer_sample_counts = CancerSampleCount.all
  end
  
  def show_target_selection_file
    @filename = params[:filename]
    @table_array = get_target_selection_table(@filename)
    if @table_array.blank?
      respond_to do |format|
        format.html { 
            flash[:notice] = "Sorry, no file was found named #{@filename}"         
            redirect_to target_selection_path
          }
        end # /respond_to
    else
      render 'target_selection_table'
    end
  end
  
  def get_target_selection_table(fn)
    file_path = PanTcga::Application::config.data_file_root + [Version::APP_FILE_DIR, 'Selected_Target_List', fn].join('/')
    target_selection_table_array = get_table_array(file_path) if File.exists?(file_path)
    target_selection_table_array
  end
  
  def target_selection_send_data(filename = params[:filename])
    table_array = get_target_selection_table(filename)
    csv_file = to_csv(filename, table_array)
    send_data csv_file, :type => 'text/csv; charset=iso-8859-1; header=present', 
      :disposition => "attachment;filename=#{filename.gsub('.txt', '.csv')}"
  end
  
  def ppt_sendfile(filename = params[:filename])
    ppt_file = Rails.root + ['app', 'assets', 'docs', filename].join('/')
    send_file ppt_file, :type => 'application/vnd.openxmlformats-officedocument.presentationml.slideshow', 
      :disposition => "attachment;filename=#{filename}"
  end
  
  def data_download
    @cancer_types = CancerType.order('name ASC')
  end

  def send_zip_file
    file_name = params[:matrix_cancer_type] + '.zip'
    file_path = PanTcga::Application::config.data_file_root + [Version::APP_FILE_DIR, 'ZippedFiles', file_name].join('/')
    #render text: "<h2>#{file_name} at #{file_path} unavailable, coming soon</h2>"
    send_file file_path, type: 'application/zip', disposition: "attachment;filename=#{file_name}", x_sendfile: true
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_data_information_query_table.html.erb
          <div>Analysis Date: <%= DataSet::ANALYSIS_DATE %></div>
          <table class="table table-striped table-bordered table-condensed">
            <thead>
              <tr>
                  <th>Cancer Types</th>
                  <th>Total Samples</th>
                  <th>#Samples-Genes</th>
                  <th>#Samples-Proteins</th>
                  <th>#Samples-miRNA</th>
              </tr>
            </thead>
            <tbody>
              <% @cancer_types.each do |ct| %>

              <% samples_count = @samples.where(cancer_type_id: ct.id).count %>
              <% samples_genes = @gene_values.where(cancer_type_id: ct.id).length %>
              <% samples_proteins = @protein_values.where(cancer_type_id: ct.id).length %>
              <% samples_mirs = @mir_values.where(cancer_type_id: ct.id).length %>
              <tr> 
                <td><%= ct.abbreviation %></td>
                <td><%= samples_count %></td>
                <td><%= samples_genes %></td>
                <td><%= samples_proteins %></td>
                <td><%= samples_mirs %></td>
              </tr>

              <% end %>
            </tbody>
          </table>

app/views/static_pages/_data_information_static_table.erb
<div>Broad Firehose Version: Version::CURRENT_VERSION.release_date </div>
<table class="table table-striped table-bordered table-condensed">
<thead>
  <tr>
    <th>Cancer Types</th>
    <th>Total Samples</th>
    <th>#Samples-Genes</th>
    <th>#Samples-Proteins</th>
    <th>#Samples-miRNA</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td>ACC</td>
    <td>92</td>
    <td>75</td>
    <td>80</td>
    <td>46</td>
  </tr>
  <tr>
    <td>BLCA</td>
    <td>412</td>
    <td>388</td>
    <td>409</td>
    <td>127</td>
  </tr>
  <tr>
    <td>BRCA</td>
    <td>1098</td>
    <td>945</td>
    <td>755</td>
    <td>410</td>
  </tr>
  <tr>
    <td>CESC</td>
    <td>307</td>
    <td>190</td>
    <td>307</td>
    <td>173</td>
  </tr>
  <tr>
    <td>COADREAD</td>
    <td>628</td>
    <td>476</td>
    <td>295</td>
    <td>461</td>
  </tr>
  <tr>
    <td>ESCA</td>
    <td>185</td>
    <td>0</td>
    <td>184</td>
    <td>126</td>
  </tr>
  <tr>
    <td>GBM</td>
    <td>610</td>
    <td>111</td>
    <td>0</td>
    <td>214</td>
  </tr>
  <tr>
    <td>HNSC</td>
    <td>528</td>
    <td>496</td>
    <td>486</td>
    <td>212</td>
  </tr>
  <tr>
    <td>KICH</td>
    <td>66</td>
    <td>66</td>
    <td>66</td>
    <td>0</td>
  </tr>
  <tr>
    <td>KIRC</td>
    <td>537</td>
    <td>446</td>
    <td>254</td>
    <td>454</td>
  </tr>
  <tr>
    <td>KIRP</td>
    <td>291</td>
    <td>161</td>
    <td>291</td>
    <td>207</td>
  </tr>
  <tr>
    <td>LAML</td>
    <td>200</td>
    <td>160</td>
    <td>0</td>
    <td>0</td>
  </tr>
  <tr>
    <td>LGG</td>
    <td>516</td>
    <td>510</td>
    <td>512</td>
    <td>258</td>
  </tr>
  <tr>
    <td>LIHC</td>
    <td>377</td>
    <td>189</td>
    <td>372</td>
    <td>0</td>
  </tr>
  <tr>
    <td>LUAD</td>
    <td>582</td>
    <td>485</td>
    <td>450</td>
    <td>181</td>
  </tr>
  <tr>
    <td>LUSC</td>
    <td>504</td>
    <td>178</td>
    <td>342</td>
    <td>195</td>
  </tr>
  <tr>
    <td>OV</td>
    <td>605</td>
    <td>216</td>
    <td>453</td>
    <td>412</td>
  </tr>
  <tr>
    <td>PAAD</td>
    <td>185</td>
    <td>145</td>
    <td>178</td>
    <td>106</td>
  </tr>
  <tr>
    <td>PCPG</td>
    <td>179</td>
    <td>161</td>
    <td>179</td>
    <td>79</td>
  </tr>
  <tr>
    <td>PRAD</td>
    <td>498</td>
    <td>419</td>
    <td>494</td>
    <td>0</td>
  </tr>
  <tr>
    <td>SKCM</td>
    <td>470</td>
    <td>290</td>
    <td>351</td>
    <td>169</td>
  </tr>
  <tr>
    <td>STAD</td>
    <td>443</td>
    <td>255</td>
    <td>395</td>
    <td>264</td>
  </tr>
  <tr>
    <td>THCA</td>
    <td>503</td>
    <td>397</td>
    <td>502</td>
    <td>222</td>
  </tr>
  <tr>
    <td>UCEC</td>
    <td>559</td>
    <td>241</td>
    <td>411</td>
    <td>200</td>
  </tr>
  <tr>
    <td>UCS</td>
    <td>57</td>
    <td>56</td>
    <td>56</td>
    <td>48</td>
  </tr>
  </tbody>
</table>

app/views/static_pages/_data_information_table.html.erb
<div>Broad Firehose Version: <%= Version::CURRENT_VERSION.data_set.analysis_date %> </div>
<table class="table table-striped table-bordered table-condensed">
  <thead>
  <tr>
    <th>Cancer Types</th>
    <th>Total Samples</th>
    <th>#Samples-Genes</th>
    <th>#Samples-Proteins</th>
    <th>#Samples-miRNA</th>
  </tr>
  </thead>
  <tbody>
  <% @cancer_types.each do |ct| %>
      <% sample_counts = @cancer_sample_counts.find(ct.id) %>
      <tr>
        <td><%= ct.abbreviation %></td>
        <td><%= sample_counts.sample_count %></td>
        <td><%= sample_counts.sample_gene_count %></td>
        <td><%= sample_counts.sample_protein_count %></td>
        <td><%= sample_counts.sample_mir_count %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>

<div class="jumbotron">
  <h1>About</h1>
  <div class="panel panel-default">
    <div class="panel-body">
      <p>The Stanford-Cancer Genome Atlas Project is developed and maintained by Ji Research Group at Stanford School of Medicine.</p>
      <hr>
      <h3 style="padding-left:14px;">Project Contributors:</h3>
      <p>
        HoJoon Lee, Phd., Author<br>
        Hanlee Ji, M.D., P.I.<br>
        Jennifer Palm, Web Application<br>
        Sue Grimes, Database modeling advisor<br>
      </p>
      <hr>
      <p>Publication: <%= link_to "Genome Medicine 2015, 7:112", 'http://www.genomemedicine.com/content/7/1/112', target: '_blank' %></p>
                           <!-- style:"font-size:smaller; font-style:italic; font-weight:bold" -->
      <hr>
      <p>Queries and comments: <%= mail_to "pan-tcga-project@stanford.edu" %></p>
    </div><!-- /panel body -->
  </div><!-- /panel -->

  <div class="panel panel-default">
    <div class="panel-body">
	  <h3 style="padding-left:14px;">Version History:</h3>
      <table class="table table-striped table-condensed table-bordered">
        <thead>
        <tr>
          <th>Version</th>
          <th>Release Date</th>
          <th>Broad Firehose</th>
          <th>#Cancer Types</th>
          <th>#Clinical Params</th>
          <th>Displayed Candidates</th>
        </tr>
        </thead>
        <tbody>
        <% @versions.each do |version| %>
            <tr>
              <% if version.version_number == '1.0' and Version::CURRENT_VERSION.version_number != '1.0' %>
                  <td class="text-center"><%= link_to version.version_number, 'http://genomeportal.stanford.edu/pan-tcga-v1', target: '_blank' %></td>
              <% else %>
                  <td class="text-center"><%= version.version_number %></td>
              <% end %>
              <td class="text-center"><%= version.release_date %></td>
              <td class="text-center"><%= version.data_set.analysis_date %></td>
              <td class="text-center"><%= version.nr_cancer_types %></td>
              <td class="text-center"><%= version.nr_clinical_params %></td>
              <td class="text-center"><%= version.candidate_filter %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div><!-- /panel body -->
  </div><!-- /panel -->
  <% if @versions.size > 1 %>
    <p style="font-size:small; color:cornflowerblue">Previous versions available by clicking on version number above</p>
  <% end %>
</div>

app/views/static_pages/analysis_pipeline.html.erb
<% provide(:title, 'Analysis Pipeline') %>

<div class="center jumbotron">
  <h1>Analysis Pipeline</h1>
  <div class="panel panel-default">
    <div class="panel-body">
      <%= image_tag("AnalysisPipeLineNew.jpg", style: "width:100%", alt:"analysis pipeline") %>
    </div><!-- /panel body -->
  </div><!-- /panel -->
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

<div class="center jumbotron">
  <h1>Contact Project Members</h1>
  <p>This is the contact page for the Pan TCGA Project</p>
</div>

app/views/static_pages/data_download.html.erb
<% provide(:title, 'Data Download') %>

<div class="center jumbotron">
  <h1>Data Download</h1>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Download Cancer Type Matrix  
      <div id="hint" style="display: inline"><a href="#" title="aggregation of genomic values per sample">(Info)</a></div> [zip]
      </h3>
    </div>
    <div class="panel-body">

      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_tag send_zip_file_path, id: 'download_matrix_zip' do  %>
            <%= label_tag 'sel_clin_param', 'Select Cancer Type Matrix Download', class: 'sr-only' %>
            <div class="input-group input-group-lg">
              <%= select_tag :matrix_cancer_type, 
                    options_for_select(
                      get_cancer_types_for_select.order('abbreviation ASC').collect {|ct| [ ct.abbr_name, ct.abbreviation ] },
                      (params[:matrix_cancer_type] ? params[:matrix_cancer_type] : "")
                    ), 
                    :prompt => "Select Cancer Type Matrix Download",  
                    class: "form-control" %>
              <span class="input-group-btn">
                <%= submit_tag "Go", class: "btn btn-info" %>
              </span>
            </div><!-- /input-group -->
          <% end %><!-- /form --> 
          <div id="error_cp"></div>  
        </div><!-- /col -->
      </div><!-- /row -->

    </div><!-- /panel body -->
  </div><!-- /panel -->
</div>

app/views/static_pages/data_information.html.erb
<% provide(:title, 'Data Information') %>
<div class="center jumbotron">
  <h1>Data Information</h1>
  <div class="panel panel-default">
    <div class="panel-body">
      <!--%= render 'data_information_query_table' # DO THIS ON INITIAL DATA LOAD, UNCOMMENT QUERIES IN CONTROLLER, RUN, THEN COPY SOURCE TABLE TO 'data_information_table' (sudo-caching) %-->
      <%= render 'data_information_table' %>
    </div><!-- /panel body -->
  </div><!-- /panel -->
</div>

app/views/static_pages/faq.html.erb
<% provide(:title, 'FAQ') %>

<div class="center jumbotron">
  <h1>Frequently Asked Questions</h1>
  <p>This is the faq page for using Pan TCGA</p>
</div>

app/views/static_pages/project_overview.html.erb
<% provide(:title, 'Project Overview') %>

<div class="jumbotron">
  <h1>Project Overview</h1>
  <div class="panel panel-default">
    <div class="panel-body">
      <%= image_tag("ProjectOverview3.jpg", style: "width:100%", alt:"project overview") %>
      <p></p>
      <p>The <%= link_to "NIH Cancer Genome Atlas", 'http://cancergenome.nih.gov/', target: '_blank' %> (TCGA) project has generated enormous data sets covering &gt; 20 malignancies and provides many valuable insights into the underlying genetic and genomic basis of cancer.  However, exploring the association between TCGA results and clinical phenotype remains a challenge, particularly for individuals lacking formal bioinformatics training.  This will be an important exploratory step towards the clinical translation of cancer genomic/proteomic data.  Several websites such as cBio portal or UCSC genome browser make TCGA data accessible but these sites have few interactive features for querying clinically-relevant phenotypic associations with cancer drivers.  To enable exploration of the clinical associations of the TCGA data, we developed the <%= link_to "Stanford-TCGA Portal", 'http://genomeportal.stanford.edu/pan-tcga', target: '_blank' %>.  Using a web/mobile interface, this website enables easy navigation of cancer genomic/proteomic/clinical data provided by the TCGA and poses clinically relevant questions.  For example, &quot;What genes are associated with advanced breast cancer?&quot; or &quot;What is the frequency of copy number deletion of APC for samples with/without PIK3CA mutations?&quot;.</p>

    <p>The Stanford-TCGA portal interface provides querying of TCGA data in three different ways:
      <ol style="list-style-type: lower-roman;">
        <li>search for clinically relevant genes/micro RNAs (miRs)/proteins by names, cancer types or clinical parameters</li>
        <li>profile genomic/proteomic changes by clinical parameters in a cancer type</li>
        <li>test two-hit hypotheses.</li>
      </ol>
    </p>

    <p>Any user can easily navigate the lists of these identified genes through the Stanford-TCGA Portal.  SQL queries run in the background and show the results on our portal according to user’s input.  To derive these associations, we relied on elastic-net estimates of optimal multiple linear regularized regression; we relied on clinical parameters in the space of multiple genomic/proteomic features provided by the TCGA data.  We identified the set of top gene predictors (by 10 fold cross validation) of each clinical parameter for each cancer.  The robustness of results was estimated by bootstrapping with 2,000 iterations.  As a proof-of-concept, we demonstrated this approach’s utility in the TCGA colorectal cancer data (<%= link_to "HoJoon Lee et al., BMC Medical Genomics 2013", 'http://www.biomedcentral.com/1755-8794/6/54', target: '_blank' %>) and we have since expanded our analysis to include nearly all TCGA malignancies.  We identify clinically relevant genes/miRs/proteins by our statistical analysis, some which has been previously described, from 25 cancer types with 18 clinical parameters such as clinical stage or smoking history.</p>

    <p>In summary, the Stanford-TCGA Portal enables the cancer research community and others to fully utilize TCGA data.  With its straightforward web/mobile interface, it provides simple yet clinically relevant associations of TCGA results.  Thus, one can examine queries and test hypothesis regarding genomic/proteomic alterations in cancers from any time and place.</p>

      <hr>
      <p>Queries and comments: <%= mail_to "pan-tcga-project@stanford.edu" %></p>
    </div><!-- /panel body -->
  </div><!-- /panel -->
</div>

app/views/static_pages/target_selection.html.erb
<% provide(:title, 'Target Selection') %>

<div class="jumbotron">
  <h1>Target Selection</h1>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">    
      <div class="panel panel-default">
        <div class="panel-body">
          <h2>Gene Selection</h2>
          <p>
            <ol>
              <li>COSMIC cancer genes: As of February 2015, COSMIC database listed <%= link_to "538 genes", show_target_selection_file_path(filename:'COSMIC.txt') %> as cancer genes that have been implicated in cancer development from the scientific literature. The list of genes, cancer_gene_census.tsv, was downloaded from <%= link_to 'their website', 'http://cancer.sanger.ac.uk/cancergenome/projects/cosmic/download', target: '_blank' %></li>
              <li>Genes from TCGA studies: we included genes with significant mutations or within focal amplifications/deletions according to Broad Firehose analysis (2015_04_02 version).
                <ol style="list-style-type:lower-roman">
                  <li>Significantly mutated genes: Broad Firehose used MutSig 2CV. Total <%= link_to "676 genes", show_target_selection_file_path(filename:'MutSig.txt') %> had significant mutations from 25 cancer types with false discovery rate < 0.001</li>
                  <li>Genes in significant focal copy number change: Broad Firehose used GISTIC 2.0. Total <%= link_to "1,163 genes", show_target_selection_file_path(filename:'GeneDel.txt') %> were in focal deletion while <%= link_to "373 genes", show_target_selection_file_path(filename:'GeneAmp.txt') %> were in focal amplification.</li>
                </ol>
              </li>
            </ol>
            <p><strong><em>Collectively <%= link_to "2,180 genes", show_target_selection_file_path(filename:'TargetGenes.txt') %> genes were included in our study.</em></strong></p>
          </p>
          <h2>miR Selection</h2>
          <p>We included all <%= link_to "1,751 miR", show_target_selection_file_path(filename:'AllmiR.txt') %> in miR-Sequencing data from 25 cancers</p>
          <h2>Protein selection</h2>
          <p>We included all <%= link_to "228 proteins", show_target_selection_file_path(filename:'Allprotein.txt') %> in RPPA data from 25 cancers</p>
        </div><!-- /panel body --> 
      </div><!-- /panel -->
    </div><!-- /col -->
  </div><!-- /row -->
</div>

app/views/static_pages/target_selection_table.html.erb
<% provide(:title, 'Target Selection') %>

<div class="jumbotron target-selection">
  <h1>Target Selection</h1>
  <div class="panel panel-default">
    <div class="panel-body">
      <div class="text-right">
      <strong>DOWNLOAD: <%= link_to 'CSV', target_selection_send_data_path(filename: @filename) %></strong>
      </div>
      <% theads = @table_array.shift %>
      <table id="target_selection" align="center" class="table table-striped table-condensed table-bordered" style="width:65%">
        <thead>
        <tr>
          <th style="font-weight:bold" colspan="<%= @table_array[0].length %>"><%= @filename.gsub('_', ' ').gsub('.txt', '')%></th>	
        </tr>
        <tr>
          <% theads.each do |heading1| %>
          <th style="padding:2px; font-weight:500"><%= heading1 %></th>
          <% end %>
        </tr>
        </thead>
        <tbody>
        <% @table_array.each do |row| %>
        <tr>
        	<% row.each do |item| %>
          <td><%= raw item.gsub(',', "<br>") if item %></td>
          <% end %>
        </tr>
        <% end %>
        </tbody>
      </table>
    </div><!-- /panel body -->
  </div><!-- /panel -->
</div><!-- /jumbotron -->

app/views/static_pages/target_selection_v1.html.erb
<% provide(:title, 'Target Selection') %>

<div class="jumbotron">
  <h1>Target Selection</h1>
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div class="panel panel-default">
        <div class="panel-body">
          <h2>Gene Selection</h2>
          <p>
          <ol>
            <li>COSMIC cancer genes: As of February 2014, COSMIC database listed <%= link_to "522 genes", show_target_selection_file_path(filename:'COSMIC_0218_2014.txt') %> as cancer genes that have been implicated in cancer development from the scientific literature. The list of genes, cancer_gene_census.tsv, was downloaded from <%= link_to 'their website', 'http://cancer.sanger.ac.uk/cancergenome/projects/cosmic/download', target: '_blank' %></li>
            <li>Genes from TCGA studies: we included genes with significant mutations or within focal amplifications/deletions according to Broad Firehose analysis (2014_01_16 version).
              <ol style="list-style-type:lower-roman">
                <li>Significantly mutated genes: Broad Firehose used MutSig v2.0. Total <%= link_to "448 genes", show_target_selection_file_path(filename:'MutSig.txt') %> had significant mutations from 17 cancer types with false discover rate < 0.05</li>
                <li>Genes in significant focal copy number change: Broad Firehose used GISTIC 2.0. Total <%= link_to "1,266 genes", show_target_selection_file_path(filename:'GeneDel.txt') %> were in focal deletion while <%= link_to "357 genes", show_target_selection_file_path(filename:'GeneAmp.txt') %> were in focal amplification.</li>
              </ol>
            </li>
          </ol>
          <p><strong><em>Collectively <%= link_to "2,227 genes", show_target_selection_file_path(filename:'TargetGenes.txt') %> genes were included in our study.</em></strong></p>
          </p>
          <h2>miR Selection</h2>
          <p>We included all <%= link_to "413 miR", show_target_selection_file_path(filename:'AllmiR.txt') %> in miR-Sequencing data from 17 cancers</p>
          <h2>Protein selection</h2>
          <p>We included all <%= link_to "528 proteins", show_target_selection_file_path(filename:'Allprotein.txt') %> in RPPA data from 17 cancers</p>
        </div><!-- /panel body -->
      </div><!-- /panel -->
    </div><!-- /col -->
  </div><!-- /row -->
</div>

app/views/static_pages/tutorial_overview.html.erb
<% provide(:title, 'Tutorial') %>

<div class="center jumbotron">
  <h1>Tutorial Information</h1>
  <div class="panel panel-default">
    <div class="panel-body">
      <iframe src="//www.slideshare.net/slideshow/embed_code/43488141" width="595" height="485" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC; border-width:1px; margin-bottom:5px; max-width: 100%;" allowfullscreen> </iframe>
    </div><!-- /panel body -->
  </div><!-- /panel -->
</div>

  