config/routes.rb
PanTcga::Application.routes.draw do
  
  root  'welcome#index', via: [:get, :post]
  
  match 'about', to: 'static_pages#about', via: 'get'
  match 'faq', to: 'static_pages#faq', via: 'get'
  match 'project_overview', to: 'static_pages#project_overview', via: 'get'
  match 'analysis_pipeline', to: 'static_pages#analysis_pipeline', via: 'get'
  match 'target_selection', to: 'static_pages#target_selection', via: 'get'
  match 'data_information', to: 'static_pages#data_information', via: 'get'
  match 'data_download', to: 'static_pages#data_download', via: 'get'
  match 'show_target_selection_file' => 'static_pages#show_target_selection_file', via: 'get'
  match 'target_selection_send_data' => 'static_pages#target_selection_send_data', via: 'get'
  match 'tutorial' => 'static_pages#tutorial_overview', via: 'get'
  match 'ppt_sendfile' => 'static_pages#ppt_sendfile', via: 'get'
  match 'send_zip_file' => 'static_pages#send_zip_file', via: [:get, :post]
  
  match '/get_cancer_type', to: 'cancer_types#get_cancer_type', via: 'post'

  match 'high_level_summary', to: 'high_level_summaries#index', via: [:get, :post]
  match 'show_high_level_summary_panels', to: 'high_level_summaries#show_high_level_summary_panels', via: [:get, :post]
  match 'high_level_summary_table', to: 'high_level_summaries#show_table', via: 'post'
  match 'high_level_data_analysis', to: 'high_level_summaries#high_level_data_analysis', via: [:get, :post]
  match 'query_clin_param_vals', to: 'high_level_summaries#query_clin_param_vals', via: [:get, :post]

  match 'outcome_summary', to: 'outcome_summaries#index', via: [:get, :post]
  match 'search_outcome_tables', to: 'outcome_summaries#search_outcome_tables', via: [:get, :post]
  match 'send_file' => 'outcome_summaries#send_file', via: [:get, :post]

  match 'matrix_query', to: 'matrix#index', via: [:get, :post]
  match 'target_genomic_query', to: 'matrix#target_genomic_by_target_genomic', via: [:get, :post] 
  match 'get_matrix_data', to: 'matrix#get_matrix_data', via: [:get, :post] 

  

end

app/models/cancer_type.rb
class CancerType < ActiveRecord::Base

  has_many :target_sets
  has_many :samples
  has_many :high_level_summaries
  has_many :clinical_parameter_values
  has_many :target_gene_values
  has_many :target_protein_values
  has_many :target_gene_values

  validates :name, presence: true, uniqueness: true
  validates :abbreviation, presence: true, uniqueness: true

  ID_EXCLUDES = self.where(abbreviation: ['COAD', 'READ']).pluck(:id)

  def abbr_name
  	abbreviation + '-' + name
  end

end

app/models/clinical_parameter.rb
class ClinicalParameter < ActiveRecord::Base
  has_many :high_level_summaries
  has_many :clinical_parameter_values
  has_many :samples, through: :clinical_parameter_values

  validates :name, presence: true, uniqueness: true
end

app/models/data_set.rb
class DataSet < ActiveRecord::Base

	has_many :high_level_summaries
	has_many :clinical_parameter_values
  has_many :target_gene_values
  has_many :target_protein_values
  has_many :target_gene_values

	VALID_DATE_REGEX = /\A\d{4}-\d{2}-\d{2}/
	validates :analysis_date, presence: true, 
	                      format: VALID_DATE_REGEX,
	                      uniqueness: true

	ANALYSIS_DATE = self.last.analysis_date
end

app/models/gene.rb
class Gene < ActiveRecord::Base
  has_many :outcome_summaries, as: :target
  has_many :target_gene_values
  has_many :gene_cn_frequencies
  has_many :gene_mut_frequencies
  
  validates :name, presence: true, uniqueness: true
end

app/models/gene_cn_frequency.rb
class GeneCnFrequency < ActiveRecord::Base
  belongs_to :cancer_type
  belongs_to :data_set
  belongs_to :target_set
  belongs_to :gene
end

app/models/gene_mut_frequency.rb
class GeneMutFrequency < ActiveRecord::Base
  belongs_to :cancer_type
  belongs_to :data_set
  belongs_to :target_set
  belongs_to :gene
end

app/models/genomic.rb
class Genomic < ActiveRecord::Base
  has_many :high_level_summary_values
  has_many :target_gene_values
  has_many :target_protein_values
  has_many :target_gene_values

  validates :name, presence: true, uniqueness: true
  
  CN_ID = 4
  MAF_ID = 5

  def readable_name
    (name_text.blank? ? name : name_text)
  end

end

app/models/genomic_value.rb
class GenomicValue < ActiveRecord::Base
  belongs_to :cancer_type
  belongs_to :data_set
  belongs_to :target_set
  belongs_to :genomic
  belongs_to :sample
  belongs_to :target, polymorphic: true
end

app/models/high_level_genomic.rb
class HighLevelGenomic < ActiveRecord::Base
  has_many :high_level_summaries
end

app/models/mir.rb
class Mir < ActiveRecord::Base
  has_many :outcome_summaries, as: :target
  has_many :target_mir_values

  validates :name, presence: true, uniqueness: true
end

app/models/outcome_summary.rb
class OutcomeSummary < ActiveRecord::Base
  belongs_to :cancer_type
  belongs_to :data_set
  belongs_to :target_set
  belongs_to :high_level_genomic
  belongs_to :genomic
  belongs_to :clinical_parameter
  belongs_to :clinical_parameter_sub_cat
  belongs_to :gene
  belongs_to :target, polymorphic: true

  def p_values
    p_vals = [pval_copy_number, pval_m_rna_expression, pval_methylation, pval_mutation, pval_mi_rna_expression, pval_protein_expression]
    p_vals.compact
  end

end

app/models/protein.rb
class Protein < ActiveRecord::Base
  has_many :outcome_summaries, as: :target
  has_many :target_protein_values

  validates :name, presence: true, uniqueness: true
end

app/models/sample.rb
class Sample < ActiveRecord::Base
  belongs_to :cancer_type
  belongs_to :data_set
  has_many   :clinical_parameter_values
  has_many   :clinical_parameters, through: :clinical_parameter_values
  has_many :target_gene_values
  has_many :target_protein_values
  has_many :target_gene_values

  #validates :sample_code, presence: true, uniqueness: true

end

app/models/target_gene_value.rb
class TargetGeneValue < ActiveRecord::Base
  belongs_to :cancer_type
  belongs_to :data_set
  belongs_to :gene
  belongs_to :genomic
  belongs_to :sample
end

app/models/target_mir_value.rb
class TargetMirValue < ActiveRecord::Base
  belongs_to :cancer_type
  belongs_to :data_set
  belongs_to :mir
  belongs_to :genomic
  belongs_to :sample 
end

app/models/target_set.rb
class TargetSet < ActiveRecord::Base

  belongs_to :cancer_type

  has_many :samples
  has_many :high_level_summaries
  has_many :clin_par_val_targ_sets

  VALID_TARGETSET_REGEX = /\A[a-zA-Z0-9-]+\z/ #targetset token will be part of filename which uses "_" as seperator
  validates :name, presence: true, 
                   format: VALID_TARGETSET_REGEX,
                   uniqueness: true

  def flag_name
    id_to_flag = {1 => 'target_genes_flag', 2 => 'all_protein_flag', 3 => 'all_mir_flag'}
    return id_to_flag[id]
  end

  def klass_name
    id_to_class = {1 => 'Gene', 2 => 'Protein', 3 => 'Mir'}
    return id_to_class[id]
  end

  def target_text
    return (id == 3 ? 'miR' : klass_name)
  end
end

app/models/version.rb
class Version < ActiveRecord::Base
	belongs_to :data_set

	ALLVERSIONS = self.includes(:data_set).order("release_date DESC").all
  CURRENT_VERSION = self.last
  APP_FILE_DIR = (CURRENT_VERSION.version_number == '1.0' ? 'Version1' : 'Current')

  def pvalue_msg
    return (version_number == '1.0' ? 'p-values not available in this version': 'p=0 indicates p < 1.0e-08')
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    reset_session
    @genes = Gene.pluck(:name)
    @proteins = Protein.pluck(:name)
    @mirs = Mir.pluck(:name)  	
  end
end

app/helpers/matrix_helper.rb
module MatrixHelper

  def get_genomic_readable_name(genomic_id)
    genomic_readable_name = Genomic.find(genomic_id).readable_name
    genomic_readable_name
  end
 
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper

  def get_clinical_parameters_for_select
    #excludes = [2]  (Previously DaysToDeath, no longer in table)
    clinical_parameters_table = Arel::Table.new(:clinical_parameters)
    #clinical_parameters_without_excludes = ClinicalParameter.where(clinical_parameters_table[:id].not_in excludes)
    clinical_parameters_without_excludes = ClinicalParameter.all
    clinical_parameters_without_excludes
  end
  
  def get_genomic_types_for_select1
    #excludes = [12,13,5] # all methylations
    genomics_table = Arel::Table.new(:genomics)
    #genomics_without_excludes = Genomic.where(genomics_table[:id].not_in excludes)
    genomics_without_excludes = Genomic.all
    genomics_without_excludes
  end
  
  def get_genomic_types_for_select2
    includes = [4,5]   # Copy number, MAF  # Fix this later to not rely on id
    genomics_table = Arel::Table.new(:genomics)
    genomics_without_excludes = Genomic.where(genomics_table[:id].in includes)
    genomics_without_excludes
  end

end

app/views/welcome/_query_for_matrix_form.html.erb
          <%= form_tag matrix_query_path,
              id: 'query_for_matrix', 
              class: '', method: :get do  %><!-- form for query_for_matrix -->

              <div class="row">
                <div class="col-xs-6">
                  <div class="form-group pull-right">
                    <label class="sr-only" for="">Target</label>
                    <div class="nowrap_space" style="display:inline">
                      Target:&nbsp;
                      <input type="radio" id_name="query_for_matrix_target_set_id" name="query_for_matrix[target_set_id]" id="query_for_matrix_target_set_id1" checked="checked" value="1">&nbsp;Gene&nbsp;&nbsp;
                      <input type="radio" id_name="query_for_matrix_target_set_id" name="query_for_matrix[target_set_id]" id="query_for_matrix_target_set_id2" value="2">&nbsp;Protein&nbsp;&nbsp;
                      <input type="radio" id_name="query_for_matrix_target_set_id" name="query_for_matrix[target_set_id]" id="query_for_matrix_target_set_id3" value="3">&nbsp;miR
                    </div>
                  </div>
                </div><!-- /col -->
                <div class="col-xs-6">
                  <div class="form-group">
                    <label class="sr-only" for="">Enter Target Name</label>
                    <%= text_field_tag "query_for_matrix[gene_name]", nil, 
                        class: 'form-control typeahead_gene_matrix', 
                        placeholder: 'Enter Gene' %>
                    <%= text_field_tag "query_for_matrix[protein_name]", nil, 
                        class: 'form-control typeahead_protein_matrix', 
                        placeholder: 'Enter Protein', style: "display: none; left: -4px" %>
                    <%= text_field_tag "query_for_matrix[mir_name]", nil, 
                        class: 'form-control typeahead_mir_matrix', 
                        placeholder: 'Enter Mir', style: "display: none; left: -8px" %>
                  </div>
                </div><!-- /col -->
              </div><!-- /row -->

              <div class="row">
                <div class="col-xs-6">
                  <div class="form-group">
                    <label class="sr-only" for="">Select Cancer Type</label>
                    <%= select_tag "query_for_matrix[cancer_type_id]", options_for_select(get_cancer_types_for_select.order('abbreviation ASC').collect {|ct| [ ct.abbr_name, ct.id ] }), :prompt => "Select Cancer Type",  class: "form-control" %>
                  </div> 
                </div><!-- /col -->
                <div class="col-xs-6">
                  <div class="form-group">
                    <label class="sr-only" for="">Select Clinical Parameter</label>
                    <%= select_tag "query_for_matrix[clinical_parameter_id]", options_for_select(get_clinical_parameters_for_select.order('name ASC').collect {|cp| [ cp.name, cp.id ] }), :prompt => "Select Clinical Parameter",  class: "form-control" %>
                  </div> 
                </div><!-- /col -->
              </div><!-- /row -->

            <%= submit_tag "Submit", class: "btn btn-info" %>
          <% end %><!-- /form for query_for_matrix -->
          <div id="error_query_for_matrix"></div>
 

app/views/welcome/_query_for_outcome_summary_forms.html.erb
              <div class="row">
                <div class="col-sm-12">
                  <div class="panel panel-info"> 
                    <div class="panel-heading"><h3 class="panel-title">Check if Gene/Protein/miR of your interest is associated with Clinical Parameters
                  </h3></div>
                    <div class="panel-body">
                      <%= form_tag outcome_summary_path,
                          id: 'query_for_outcome_summary',
                          method: 'get',
                          class: 'form-inline' do  %><!-- form for query_for_outcome_summary -->
                        <div class="form-group">
                          <label class="sr-only" for="">Target</label>
                          <div class="nowrap_space" style="display:inline">
                            Target:&nbsp;
                            <input type="radio" id_name="query_for_outcome_summary" name="query_for_outcome_summary[target_set_id]" id="query_for_outcome_summary_target_set_id1" checked="checked" value="1">&nbsp;Gene&nbsp;&nbsp;
                            <input type="radio" id_name="query_for_outcome_summary" name="query_for_outcome_summary[target_set_id]" id="query_for_outcome_summary_target_set_id2" value="2">&nbsp;Protein&nbsp;&nbsp;
                            <input type="radio" id_name="query_for_outcome_summary" name="query_for_outcome_summary[target_set_id]" id="query_for_outcome_summary_target_set_id3" value="3">&nbsp;miR&nbsp;&nbsp;
                          </div>
                        </div>
                        <div class="form-group">
                          <label class="sr-only" for="">Query For Outcome Summary</label>
                          <%= text_field_tag "query_for_outcome_summary[gene_name]", nil, 
                              class: 'form-control typeahead_gene_outcome', 
                              placeholder: 'Enter Gene' %>
                          <%= text_field_tag "query_for_outcome_summary[protein_name]", nil, 
                              class: 'form-control typeahead_protein_outcome', 
                              placeholder: 'Enter Protein', style: "display: none; left: -4px" %>
                          <%= text_field_tag "query_for_outcome_summary[mir_name]", nil, 
                              class: 'form-control typeahead_mir_outcome', 
                              placeholder: 'Enter Mir', style: "display: none; left: -8px" %>
                        </div>
                        <%= submit_tag "Submit", class: "btn btn-info" %>
                      <% end %><!-- /form  --> 
                      <div id="error_query_by_target"></div>
                    </div><!-- /panel body -->
                  </div><!-- /panel -->
                </div><!-- /col -->              
              </div><!-- /row -->

              <div class="row">
                <div class="col-xs-6">
                  <div class="panel panel-info"> 
                    <div class="panel-heading"><h3 class="panel-title">What Cancer Type are you interested in?</h3></div>
                    <div class="panel-body">
                      <%= form_tag high_level_summary_path, id: 'choose_cancer_type' do  %>
                      <%= label_tag 'cancer_type', 'Select Cancer Type', class: 'sr-only' %>
                      <div class="input-group input-group-md">
                        <%= select_tag :cancer_type_id, options_for_select(get_cancer_types_for_select.order('abbreviation ASC').collect {|ct| [ ct.abbr_name, ct.id ] }), :prompt => "Select Cancer Type",  class: "form-control" %>
                        <span class="input-group-btn">
                          <%= submit_tag "Submit", class: "btn btn-info" %>
                        </span>
                      </div><!-- /input-group -->
                      <% end %><!-- /form -->
                      <div id="error_ct"></div>      
                    </div><!-- /panel body -->
                  </div><!-- /panel -->
                </div><!-- /col -->
                <div class="col-xs-6">
                  <div class="panel panel-info"> 
                    <div class="panel-heading"><h3 class="panel-title">What Clinical Parameter are you interested in?</h3></div>
                    <div class="panel-body">
                      <%= form_tag high_level_summary_path, id: 'choose_clinical_parameter' do  %>
                      <%= label_tag 'sel_clin_param', 'Select Clinical Parameter', class: 'sr-only' %>
                      <div class="input-group input-group-md">
                        <%= select_tag :clinical_parameter_id, options_for_select(get_clinical_parameters_for_select.order('name ASC').collect {|cp| [ cp.name, cp.id ] }), :prompt => "Select Clinical Parameter",  class: "form-control" %>
                        <span class="input-group-btn">
                          <%= submit_tag "Submit", class: "btn btn-info" %>
                        </span>
                      </div><!-- /input-group -->
                      <% end %><!-- /form --> 
                      <div id="error_cp"></div>     
                    </div><!-- /panel body -->
                  </div><!-- /panel -->
                </div><!-- /col -->
              </div><!-- /row -->

app/views/welcome/_query_for_target_genomic_form.html.erb
          <%= form_tag target_genomic_query_path,
              id: 'query_for_target_genomic', 
              class: '' do  %><!-- form for query_for_matrix -->
              
              <div class="row">
                <div class="col-xs-6 col-xs-offset-3">
                  <div class="form-group">
                    <label class="sr-only" for="">Select Cancer Type</label>
                    <%= select_tag "query_for_target_genomic[cancer_type_id]", options_for_select(get_cancer_types_for_select.order('abbreviation ASC').collect {|ct| [ ct.abbr_name, ct.id ] }), :prompt => "Select Cancer Type",  class: "form-control" %>
                  </div> 
                </div><!-- /col -->
              </div><!-- /row -->

              <div class="row">
                <div class="alert alert-warning" role="alert"><h5>Select First Target/Genomic pair</h5></div>
              </div><!-- /row -->
              <div class="row"> 
                <div class="col-xs-5 col-less-pad">
                  <div class="form-group pull-right">
                    <label class="sr-only" for="">Target</label>                    
                    <div class="nowrap_space" style="display:inline">
                      Target:&nbsp;
                      <input type="radio" id_name="query_for_target_genomic_target_set1_id" name="query_for_target_genomic[target_set_id]" id="query_for_target_genomic_target_set_id1a" checked="checked" value="1">&nbsp;Gene&nbsp;
                      <input type="radio" id_name="query_for_target_genomic_target_set1_id" name="query_for_target_genomic[target_set_id]" id="query_for_target_genomic_target_set_id2a" value="2">&nbsp;Protein&nbsp;
                      <input type="radio" id_name="query_for_target_genomic_target_set1_id" name="query_for_target_genomic[target_set_id]" id="query_for_target_genomic_target_set_id3a" value="3">&nbsp;miR
                    </div>                    
                  </div><!-- /form-group -->
                </div><!-- /col -->
                <div class="col-xs-3 col-less-pad">
                  <div class="form-group" style="height: 14px">
                    <label class="sr-only" for="">Enter Target Name 1</label>
                    <%= text_field_tag "query_for_target_genomic[gene_name]", nil, 
                        class: 'form-control typeahead_gene_targ_genomic1', 
                        placeholder: 'Enter Gene', style: "font-size:12px; padding: 0 6px;" %>
                    <%= text_field_tag "query_for_target_genomic[protein_name]", nil, 
                        class: 'form-control typeahead_protein_targ_genomic1', 
                        placeholder: 'Enter Protein', style: "display: none; font-size:12px; padding: 0 6px; left: -4px" %>
                    <%= text_field_tag "query_for_target_genomic[mir_name]", nil, 
                        class: 'form-control typeahead_mir_targ_genomic1', 
                        placeholder: 'Enter Mir', style: "display: none; font-size:12px; padding: 0 6px; left: -8px" %>
                  </div>
                </div><!-- /col -->
                <div class="col-xs-4">
                  <div class="form-group">
                    <label class="sr-only" for="">Select Genomic</label>
                    <%= select_tag "query_for_target_genomic[genomic_id]", "", :prompt => "Select Genomic",  class: "form-control" %>              
                  </div> 
                </div><!-- /col -->
              </div><!-- /row -->

              <div class="row">
                <div class="alert alert-warning" role="alert"><h5>Select Second Target/Genomic pair</h5></div>        
              </div><!-- /row -->
              <div class="row">
                <div class="col-xs-5 col-less-pad">
                  <div class="form-group pull-right">
                    <label class="sr-only" for="">Target</label>
                    <div class="nowrap_space" style="display:inline">
                      Target:&nbsp;
                      <input type="radio" id_name="query_for_target_genomic_target_set2_id" name="query_for_target_genomic[target_set_id2]" id="query_for_target_genomic_target_set_id1b" checked="checked" value="1">&nbsp;Gene&nbsp;&nbsp;
                      <input type="radio" id_name="query_for_target_genomic_target_set2_id" name="query_for_target_genomic[target_set_id2]" id="query_for_target_genomic_target_set_id3b" value="3">&nbsp;miR
                    </div>
                  </div>
                </div><!-- /col -->
                <div class="col-xs-3 col-less-pad">
                  <div class="form-group" style="height: 14px;">
                    <label class="sr-only" for="">Enter Target Name 2</label>
                    <%= text_field_tag "query_for_target_genomic[gene_name2]", nil, 
                        class: 'form-control typeahead_gene_targ_genomic2', 
                        placeholder: 'Enter Gene', style: "font-size:12px; padding: 0 6px;" %>
                    <%= text_field_tag "query_for_target_genomic[mir_name2]", nil, 
                        class: 'form-control typeahead_mir_targ_genomic2', 
                        placeholder: 'Enter Mir', style: "display: none; font-size:12px; padding: 0 6px; left: -4px;" %>
                  </div>
                </div><!-- /col -->
                <div class="col-xs-4">
                  <div class="form-group">
                    <label class="sr-only" for="">Select Genomic</label>
                    <%= select_tag "query_for_target_genomic[genomic_id2]", "", :prompt => "Select Genomic",  class: "form-control" %>
                  </div> 
                </div><!-- /col -->
              </div><!-- /row -->

            <%= submit_tag "Submit", class: "btn btn-info", style: "z-index:99;" %>
          <% end %><!-- /form for query_for_target_genomic -->
          <div id="error_query_for_target_genomics"></div>
          <div id="loading_icon_for_target_genomics" class="text-center" style="display:none;">
            <%= image_tag("loading_icon.gif", alt:"Loading...") %>
          </div>
 

app/views/welcome/_search_form.html.erb
<div class="search-box">
  <p><%= button_to "VIEW & SEARCH ALL GENES IN STUDY", search_all_outcome_tables_path, class:"", style: "width:289px;", 'data-no-turbolink' => true %></p>

<%= form_tag(search_input_outcome_tables_path, :method => "post", id: "search-form", 'data-no-turbolink' => true ) do %>            

<%
=begin %>
  <label>Select From Prominent Genes:</label>&nbsp;
     <%= select("genesearch", "genes_select", options_for_select(%w[TP53 KRAS APC], ""), 
     {:prompt => "Select Gene"}) %></p>
<%
=end %>

  <label>Enter one or more Genes separated by comma or space</label>
  <%= hidden_field_tag("input_search")%>
  <p><%= text_area_tag "genesearch[genes_text]", '', size: "38x3" %></p>
  <p><%= submit_tag "Search" %></p> 
<% end %>            
</div>

app/views/welcome/index_carousel.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Stanford PAN-TCGA Project</h1>
  <div class="panel panel-default">
    <div class="panel-body">
      <h2>Single Genomic analysis of multiple types of cancer tissue data gathered from the BROAD institute and UCSC.</h2>
    </div>
  </div>
  <div class="panel panel-default"> 
  <div class="panel-heading">
    <h2 class="panel-title">Query for Clinically Relevant Genes</h2>
  </div>
  <div class="panel-body">
  <div id="myCarousel" class="carousel slide">

  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li class="active" data-target="#myCarousel" data-slide-to="0">
      <!--button data-target="#myCarousel" data-slide-to="0">
        <span class="screen-reader">Cancer Types</span>
      </button-->
    </li>
    <li data-target="#myCarousel" data-slide-to="1">
      <!--button data-target="#myCarousel" data-slide-to="1">
        <span class="screen-reader">Select by Assay</span>
      </button-->
    </li>
  </ol>

    <div class="carousel-inner">

      <div id="slide1" class="item active">
        <div class="col-md-6 col-md-offset-3"> 
        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title">Select by Cancer Type</h3>
          </div>
          <div class="panel-body">
            <%= form_tag high_level_summary_path, id: 'choose_cancer_type' do  %>
            <%= label_tag 'cancer_type', 'Select Cancer Type', class: 'sr-only' %>
            <div class="input-group input-group-lg">
              <%= select_tag :cancer_type_id, options_for_select(CancerType.order('abbreviation ASC').all.collect {|ct| [ ct.abbr_name, ct.id ] }, (params[:cancer_type_id] ? params[:cancer_type_id] : "")), :prompt => "Select Cancer Type",  class: "form-control" %>
              <span class="input-group-btn">
                <%= submit_tag "Go", class: "btn btn-info" %>
              </span>
            </div><!-- /input-group -->
            <% end %><!-- /form -->
          </div><!-- /panel body -->
        </div><!-- /panel -->
        </div><!-- /col -->
      </div><!-- /item -->

      <div id="slide3" class="item">
        <div class="col-md-6 col-md-offset-3"> 
        <div class="panel panel-warning">
          <div class="panel-heading">
            <h3 class="panel-title">Select by Clinical Parameter</h3>
          </div>
          <div class="panel-body">
            <%= form_tag high_level_summary_path, id: 'choose_clinical_parameter' do  %>
            <%= label_tag 'sel_clin_param', 'Select Clinical Parameter', class: 'sr-only' %>
            <div class="input-group input-group-lg">
              <%= select_tag :clinical_parameter, options_for_select(ClinicalParameter.order('name ASC').all.collect {|cp| [ cp.name, cp.id ] }, (params[:clinical_parameter] ? params[:clinical_parameter] : "")), :prompt => "Select Clinical Parameter",  class: "form-control" %>
              <span class="input-group-btn">
                <%= submit_tag "Go", class: "btn btn-default" %>
              </span>
            </div><!-- /input-group -->
            <% end %><!-- /form -->
          </div><!-- /panel body -->
        </div><!-- /panel -->
        </div><!-- /col --> 
      </div><!-- /item -->
    </div><!-- /carousel inner -->

  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>

  </div><!-- /carousel -->
  <div id="error"></div>
  </div><!-- /outer panel content -->
  </div><!-- /outer panel for carousel -->
  
  <div id='show_clinical_features'></div>
  
  <!--%= link_to 'Clickme', '#', :'data-div2' => 'show_clinical_features', id: 'swap-div' %-->

  <!--%= link_to "Sign up now!", signup_path, class: "btn btn-default btn-lg btn-primary" %-->
</div>

app/views/welcome/index_maint.html.erb
<div class="center jumbotron">
  <div class="panel panel-info">
    <div class="panel-body">
      <h2>The Stanford-TCGA Portal: An Interactive Web Interface for Exploring the Clinical Phenotypic Relevance of Specific Cancer Drivers</h2>
    </div><!-- /panel body -->
  </div><!-- /panel -->
  <div class="row"><!-- row 1 -->
    
        <div class="panel-body">
        <p style="color:red;font-weight:bold;font-size:150%">System is down for Maintenance</p>
        <p style="color:red;font-weight:bold;font-size:150%">Expected completion Monday 6/15 </p>
        </div><!-- /panel body -->
      
  </div><!-- /row 1-->
</div><!-- /jumbotron -->