config/routes.rb
PanTcga::Application.routes.draw do
  
  root  'welcome#index', via: [:get, :post]
  
  match 'about', to: 'static_pages#about', via: 'get'
  match 'faq', to: 'static_pages#faq', via: 'get'
  match 'project_overview', to: 'static_pages#project_overview', via: 'get'
  match 'analysis_pipeline', to: 'static_pages#analysis_pipeline', via: 'get'
  match 'target_selection', to: 'static_pages#target_selection', via: 'get'
  match 'data_information', to: 'static_pages#data_information', via: 'get'
  match 'data_download', to: 'static_pages#data_download', via: 'get'
  match 'show_target_selection_file' => 'static_pages#show_target_selection_file', via: 'get'
  match 'target_selection_send_data' => 'static_pages#target_selection_send_data', via: 'get'
  match 'tutorial' => 'static_pages#tutorial_overview', via: 'get'
  match 'ppt_sendfile' => 'static_pages#ppt_sendfile', via: 'get'
  match 'send_zip_file' => 'static_pages#send_zip_file', via: [:get, :post]
  
  match '/get_cancer_type', to: 'cancer_types#get_cancer_type', via: 'post'

  match 'high_level_summary', to: 'high_level_summaries#index', via: [:get, :post]
  match 'show_high_level_summary_panels', to: 'high_level_summaries#show_high_level_summary_panels', via: [:get, :post]
  match 'high_level_summary_table', to: 'high_level_summaries#show_table', via: 'post'
  match 'high_level_data_analysis', to: 'high_level_summaries#high_level_data_analysis', via: [:get, :post]
  match 'query_clin_param_vals', to: 'high_level_summaries#query_clin_param_vals', via: [:get, :post]

  match 'outcome_summary', to: 'outcome_summaries#index', via: [:get, :post]
  match 'search_outcome_tables', to: 'outcome_summaries#search_outcome_tables', via: [:get, :post]
  match 'send_file' => 'outcome_summaries#send_file', via: [:get, :post]

  match 'matrix_query', to: 'matrix#index', via: [:get, :post]
  match 'target_genomic_query', to: 'matrix#target_genomic_by_target_genomic', via: [:get, :post] 
  match 'get_matrix_data', to: 'matrix#get_matrix_data', via: [:get, :post] 

  

end

app/models/cancer_type.rb
class CancerType < ActiveRecord::Base

  has_many :target_sets
  has_many :samples
  has_many :high_level_summaries
  has_many :clinical_parameter_values
  has_many :target_gene_values
  has_many :target_protein_values
  has_many :target_gene_values

  validates :name, presence: true, uniqueness: true
  validates :abbreviation, presence: true, uniqueness: true

  ID_EXCLUDES = self.where(abbreviation: ['COAD', 'READ']).pluck(:id)

  def abbr_name
  	abbreviation + '-' + name
  end

end

app/models/clinical_parameter.rb
class ClinicalParameter < ActiveRecord::Base
  has_many :high_level_summaries
  has_many :clinical_parameter_values
  has_many :samples, through: :clinical_parameter_values

  validates :name, presence: true, uniqueness: true
end

app/models/data_set.rb
class DataSet < ActiveRecord::Base

	has_many :high_level_summaries
	has_many :clinical_parameter_values
  has_many :target_gene_values
  has_many :target_protein_values
  has_many :target_gene_values

	VALID_DATE_REGEX = /\A\d{4}-\d{2}-\d{2}/
	validates :analysis_date, presence: true, 
	                      format: VALID_DATE_REGEX,
	                      uniqueness: true

	ANALYSIS_DATE = self.last.analysis_date
end

app/models/gene.rb
class Gene < ActiveRecord::Base
  has_many :outcome_summaries, as: :target
  has_many :target_gene_values
  has_many :gene_cn_frequencies
  has_many :gene_mut_frequencies
  
  validates :name, presence: true, uniqueness: true
end

app/models/gene_cn_frequency.rb
class GeneCnFrequency < ActiveRecord::Base
  belongs_to :cancer_type
  belongs_to :data_set
  belongs_to :target_set
  belongs_to :gene
end

app/models/gene_mut_frequency.rb
class GeneMutFrequency < ActiveRecord::Base
  belongs_to :cancer_type
  belongs_to :data_set
  belongs_to :target_set
  belongs_to :gene
end

app/models/genomic.rb
class Genomic < ActiveRecord::Base
  has_many :high_level_summary_values
  has_many :target_gene_values
  has_many :target_protein_values
  has_many :target_gene_values

  validates :name, presence: true, uniqueness: true
  
  CN_ID = 4
  MAF_ID = 5

  def readable_name
    (name_text.blank? ? name : name_text)
  end

end

app/models/genomic_value.rb
class GenomicValue < ActiveRecord::Base
  belongs_to :cancer_type
  belongs_to :data_set
  belongs_to :target_set
  belongs_to :genomic
  belongs_to :sample
  belongs_to :target, polymorphic: true
end

app/models/mir.rb
class Mir < ActiveRecord::Base
  has_many :outcome_summaries, as: :target
  has_many :target_mir_values

  validates :name, presence: true, uniqueness: true
end

app/models/outcome_summary.rb
class OutcomeSummary < ActiveRecord::Base
  belongs_to :cancer_type
  belongs_to :data_set
  belongs_to :target_set
  belongs_to :high_level_genomic
  belongs_to :genomic
  belongs_to :clinical_parameter
  belongs_to :clinical_parameter_sub_cat
  belongs_to :gene
  belongs_to :target, polymorphic: true

  def p_values
    p_vals = [pval_copy_number, pval_m_rna_expression, pval_methylation, pval_mutation, pval_mi_rna_expression, pval_protein_expression]
    p_vals.compact
  end

end

app/models/protein.rb
class Protein < ActiveRecord::Base
  has_many :outcome_summaries, as: :target
  has_many :target_protein_values

  validates :name, presence: true, uniqueness: true
end

app/models/sample.rb
class Sample < ActiveRecord::Base
  belongs_to :cancer_type
  belongs_to :data_set
  has_many   :clinical_parameter_values
  has_many   :clinical_parameters, through: :clinical_parameter_values
  has_many :target_gene_values
  has_many :target_protein_values
  has_many :target_gene_values

  #validates :sample_code, presence: true, uniqueness: true

end

app/models/target_gene_value.rb
class TargetGeneValue < ActiveRecord::Base
  belongs_to :cancer_type
  belongs_to :data_set
  belongs_to :gene
  belongs_to :genomic
  belongs_to :sample
end

app/models/target_mir_value.rb
class TargetMirValue < ActiveRecord::Base
  belongs_to :cancer_type
  belongs_to :data_set
  belongs_to :mir
  belongs_to :genomic
  belongs_to :sample 
end

app/models/target_set.rb
class TargetSet < ActiveRecord::Base

  belongs_to :cancer_type

  has_many :samples
  has_many :high_level_summaries
  has_many :clin_par_val_targ_sets

  VALID_TARGETSET_REGEX = /\A[a-zA-Z0-9-]+\z/ #targetset token will be part of filename which uses "_" as seperator
  validates :name, presence: true, 
                   format: VALID_TARGETSET_REGEX,
                   uniqueness: true

  def flag_name
    id_to_flag = {1 => 'target_genes_flag', 2 => 'all_protein_flag', 3 => 'all_mir_flag'}
    return id_to_flag[id]
  end

  def klass_name
    id_to_class = {1 => 'Gene', 2 => 'Protein', 3 => 'Mir'}
    return id_to_class[id]
  end

  def target_text
    return (id == 3 ? 'miR' : klass_name)
  end
end

app/models/version.rb
class Version < ActiveRecord::Base
	belongs_to :data_set

	ALLVERSIONS = self.includes(:data_set).order("release_date DESC").all
  CURRENT_VERSION = self.last
  APP_FILE_DIR = (CURRENT_VERSION.version_number == '1.0' ? 'Version1' : 'Current')

  def pvalue_msg
    return (version_number == '1.0' ? 'p-values not available in this version': 'p=0 indicates p < 1.0e-08')
  end
end

app/helpers/matrix_helper.rb
module MatrixHelper

  def get_genomic_readable_name(genomic_id)
    genomic_readable_name = Genomic.find(genomic_id).readable_name
    genomic_readable_name
  end
 
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper

  def get_clinical_parameters_for_select
    #excludes = [2]  (Previously DaysToDeath, no longer in table)
    clinical_parameters_table = Arel::Table.new(:clinical_parameters)
    #clinical_parameters_without_excludes = ClinicalParameter.where(clinical_parameters_table[:id].not_in excludes)
    clinical_parameters_without_excludes = ClinicalParameter.all
    clinical_parameters_without_excludes
  end
  
  def get_genomic_types_for_select1
    #excludes = [12,13,5] # all methylations
    genomics_table = Arel::Table.new(:genomics)
    #genomics_without_excludes = Genomic.where(genomics_table[:id].not_in excludes)
    genomics_without_excludes = Genomic.all
    genomics_without_excludes
  end
  
  def get_genomic_types_for_select2
    includes = [4,5]   # Copy number, MAF  # Fix this later to not rely on id
    genomics_table = Arel::Table.new(:genomics)
    genomics_without_excludes = Genomic.where(genomics_table[:id].in includes)
    genomics_without_excludes
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="pull-left">
    <small>
      <%= link_to image_tag("SU_Seal_Card_pos_89.gif", alt: "Stanford University"), 'http://stanford.edu/' %>
    </small>
    <small style="margin-left:10px">Site by <a href="http://dna-discovery.stanford.edu">Ji Research Group</a><br>
              Queries and comments:<br><%= mail_to "pan-tcga-project@stanford.edu" %><br>
              &copy; <%= Time.now.year %> Stanford University.<br>All rights reserved.
    </small>
  </div>

  <div class="pull-right">
    <nav>
      <ul>
        <li><%= link_to "Home",              root_path, method: 'post' %></li>
        <li><%= link_to "Project Overview",  project_overview_path %></li>
        <li><%= link_to "Analysis Pipeline", analysis_pipeline_path %></li>
        <li><%= link_to "Target Selection",  target_selection_path %></li>
        <li><%= link_to "Data Information",  data_information_path %></li>
        <li><%= link_to "Data Download",     data_download_path %></li>
        <li><%= link_to "Tutorial",          tutorial_path %></li>    
        <li><%= link_to "About",             about_path %></li>
      </ul>
    </nav>
 
    <table class="table table-condensed table-bordered pull-right" style="margin-bottom: 10px; width: 44%">
      <tr>
        <th colspan="2" class="text-left"><span style="font-weight: normal">Funding provided by:</span></th>
      </tr>
      <tr>
        <td style="height: 70px"><%= link_to image_tag("NCI-logo.png"), "http://www.cancer.gov/" %></td>
        <td style="height: 70px"><%= link_to image_tag("CTD2-logo-sm-bw.jpg"),  "https://ocg.cancer.gov/programs/ctd2" %></td>
      </tr>
    </table>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Stanford-TCGA-CE", root_path, method: 'post', class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav nav-pills">
        <li><%= link_to "Home",              root_path, method: 'post', class:(request.fullpath == root_path ? "active" : '') %></li>
        <li><%= link_to "Project Overview",  project_overview_path,     class:(request.fullpath == project_overview_path ? "active" : '') %></li>
        <li><%= link_to "Analysis Pipeline", analysis_pipeline_path,    class:(request.fullpath == analysis_pipeline_path ? "active" : '') %></li>
        <li><%= link_to "Target Selection",    target_selection_path,   class:(request.fullpath == target_selection_path ? "active" : '') %></li>
        <li><%= link_to "Data Information",  data_information_path,      class:(request.fullpath == data_information_path ? "active" : '') %></li>
        <li><%= link_to "Data Download",     data_download_path,         class:(request.fullpath == data_download_path ? "active" : '') %></li>
        <li><%= link_to "Tutorial", tutorial_path,                       class:(request.fullpath == tutorial_path ? "active" : '') %></li>    
        <li><%= link_to "About", about_path,                             class:(request.fullpath == about_path ? "active" : '') %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <% if Rails.env.production? %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-56745910-1', 'auto');
      ga('send', 'pageview');
    </script>
    <% end %>
  </head>
  <body class="<%= controller.controller_name %>">
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>